### ISSUE TITLE
Trouble in running init.py and train.py

### ISSUE THREAD

**Issue by yhyu13** [yasharhezaveh/Ensai#5] opened 2018-02-19 17:50 UTC
HI, I would like to report two bugs

I couldn't find the file required by `init.py`

`
starting the job...
Traceback (most recent call last):
  File "init.py", line 79, in <module>
    execfile("get_data.py")
  File "get_data.py", line 4, in <module>
    Y_all_train[0] = np.loadtxt(arcs_data_path_1 + '/parameters_train.txt')
  File "/home/hangyu5/anaconda2/envs/py2dl/lib/python2.7/site-packages/numpy/lib/npyio.py", line 858, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'data/SAURON_TEST//parameters_train.txt'`

---

The `train.py` doesn't import linked libraries

`Traceback (most recent call last):
  File "train.py", line 5, in <module>
    train_step = tf.train.AdamOptimizer(learning_rate).minimize(MeanSquareCost,var_list=train_pars)
NameError: name 'tf' is not defined
`

**Comment by yemeen** [comment] 2018-02-19 21:32
The first error is caused by the double / after SAURON_TEST. The second error can be resolved by executing init.py in the python environment. That is first run the command `python` then run `execfile('init.py')`

**Closed as completed** 2018-02-26 02:56 UTC
